file(READ "${PROJECT_ROOT}/docs/parity.json" parity_json)

string(JSON schema_version GET "${parity_json}" schema_version)
if(NOT schema_version EQUAL 1)
    message(FATAL_ERROR "unsupported parity roadmap schema: ${schema_version}")
endif()

foreach(key IN ITEMS minimum_windows language architectures api_compatibility_target)
    string(JSON ignored ERROR_VARIABLE json_error GET "${parity_json}" policy ${key})
    if(json_error)
        message(FATAL_ERROR "parity policy is missing ${key}: ${json_error}")
    endif()
endforeach()

string(JSON milestone_count LENGTH "${parity_json}" milestones)
if(NOT milestone_count EQUAL 7)
    message(FATAL_ERROR "parity roadmap must track exactly 0.2 through 0.8")
endif()

set(expected_minor 2)
set(seen_in_progress false)
set(seen_non_complete false)
math(EXPR milestone_last "${milestone_count} - 1")
foreach(index RANGE 0 ${milestone_last})
    string(JSON version GET "${parity_json}" milestones ${index} version)
    string(JSON status GET "${parity_json}" milestones ${index} status)
    string(JSON acceptance GET "${parity_json}" milestones ${index} acceptance)
    string(JSON reflection GET "${parity_json}" milestones ${index} reflection)
    if(NOT version STREQUAL "0.${expected_minor}")
        message(FATAL_ERROR "parity milestones are not contiguous at index ${index}")
    endif()
    if(NOT status MATCHES "^(planned|in_progress|complete)$")
        message(FATAL_ERROR "invalid parity status for ${version}: ${status}")
    endif()
    if(status STREQUAL "complete")
        if(seen_non_complete)
            message(FATAL_ERROR "${version} cannot complete before an earlier milestone")
        endif()
        if(NOT EXISTS "${PROJECT_ROOT}/${acceptance}")
            message(FATAL_ERROR "completed milestone ${version} has no acceptance record")
        endif()
        if(NOT EXISTS "${PROJECT_ROOT}/${reflection}")
            message(FATAL_ERROR "completed milestone ${version} has no reflection")
        endif()
        file(READ "${PROJECT_ROOT}/${acceptance}" acceptance_text)
        if(acceptance_text MATCHES "- \\[ \\]")
            message(FATAL_ERROR "completed milestone ${version} has unchecked acceptance items")
        endif()
        file(READ "${PROJECT_ROOT}/${reflection}" reflection_text)
        foreach(marker IN ITEMS "Requirement evidence" "Defects found"
                "Verification evidence" "Known limitations" "Thoroughly complete")
            if(NOT reflection_text MATCHES "${marker}")
                message(FATAL_ERROR "${version} reflection lacks section: ${marker}")
            endif()
        endforeach()
    elseif(status STREQUAL "in_progress")
        if(seen_in_progress)
            message(FATAL_ERROR "only one parity milestone may be in progress")
        endif()
        if(NOT EXISTS "${PROJECT_ROOT}/${acceptance}")
            message(FATAL_ERROR "active milestone ${version} has no acceptance checklist")
        endif()
        set(seen_in_progress true)
        set(seen_non_complete true)
    else()
        set(seen_non_complete true)
    endif()
    math(EXPR expected_minor "${expected_minor} + 1")
endforeach()

if(seen_non_complete AND NOT seen_in_progress)
    message(FATAL_ERROR
        "an unfinished parity roadmap must have one milestone explicitly in progress")
endif()
