if(NOT DEFINED PROJECT_ROOT)
    message(FATAL_ERROR "PROJECT_ROOT is required")
endif()
file(GLOB_RECURSE public_headers "${PROJECT_ROOT}/include/mwfl/*.h")
foreach(header IN LISTS public_headers)
    file(READ "${header}" contents)
    if(contents MATCHES "#[ \t]*include[ \t]*[<\"]src/")
        message(FATAL_ERROR "public header includes repository implementation path: ${header}")
    endif()
    if(contents MATCHES "mwfl::detail[ \t*&]+[A-Za-z_]")
        message(FATAL_ERROR "public header exposes mwfl::detail in a signature: ${header}")
    endif()
endforeach()
