if(NOT DEFINED PROJECT_ROOT)
    message(FATAL_ERROR "PROJECT_ROOT is required")
endif()
file(READ "${PROJECT_ROOT}/docs/api-index.json" api_index)
string(JSON schema GET "${api_index}" schema_version)
string(JSON task_count LENGTH "${api_index}" tasks)
if(NOT schema EQUAL 1 OR task_count LESS 8)
    message(FATAL_ERROR "API index is incomplete")
endif()
math(EXPR last_task "${task_count} - 1")
foreach(index RANGE ${last_task})
    foreach(field IN ITEMS task headers symbols examples tests constraints)
        string(JSON value ERROR_VARIABLE error GET "${api_index}" tasks ${index} ${field})
        if(error)
            message(FATAL_ERROR "API index task ${index} lacks ${field}: ${error}")
        endif()
    endforeach()
    foreach(collection IN ITEMS headers symbols examples tests constraints)
        string(JSON count LENGTH "${api_index}" tasks ${index} ${collection})
        if(count LESS 1)
            message(FATAL_ERROR "API index task ${index} has empty ${collection}")
        endif()
    endforeach()
endforeach()
foreach(recipe IN ITEMS add-control-wrapper native-message-interop public-api-change)
    if(NOT EXISTS "${PROJECT_ROOT}/docs/recipes/${recipe}.md")
        message(FATAL_ERROR "missing agent recipe: ${recipe}")
    endif()
endforeach()
